---
- name: add influx repo
  shell: |
    curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
    source /etc/lsb-release
    echo "deb https://repos.influxdata.com/ubuntu trusty stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
    apt-get update
  when: telegraf_install_url is not defined or telegraf_install_url == None
  changed_when: false

# by some reason update_cache flag doesn't work well
- name: Install Telegraf packages [Debian/Ubuntu]
  apt:
    name: telegraf
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: telegraf_install_url is not defined or telegraf_install_url == None
  changed_when: false

- name: Download Telegraf package via URL [Debian/Ubuntu]
  command: curl -o /tmp/telegraf-ansible-download.deb {{ telegraf_install_url }}
  when: telegraf_install_url is defined and telegraf_install_url != None

- name: Install downloaded Telegraf package [Debian/Ubuntu]
  apt:
    deb: /tmp/telegraf-ansible-download.deb
    state: present
  when: telegraf_install_url is defined and telegraf_install_url != None
